name: Build Web

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'
      - 'docs/*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate files
        run: flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: Build Web
        run: flutter build web

      - name: Upload Web Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web/
