name: Build Linux

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'
      - 'docs/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang \
            cmake \
            ninja-build \
            pkg-config \
            libgtk-3-dev \
            liblzma-dev \
            libstdc++-12-dev \
            libasound2-dev \
            libpulse-dev \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev \
            libunwind-dev \
            libmpv-dev \
            mpv \
            libavcodec-dev \
            libavformat-dev \
            libavutil-dev \
            libswscale-dev \
            libavfilter-dev \
            libavdevice-dev \
            libswresample-dev

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate files
        run: flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: Build Linux
        run: flutter build linux

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: build/linux/x64/release/bundle/
