name: Build macOS

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'
      - 'docs/*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate files
        run: flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: Build macOS
        run: flutter build macos --no-codesign

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: build/macos/Build/Products/Release/
